# uniqconsulting.collabora/tasks/install.yml
---
# - name: Install collabora CODE repo
#   yum_repository:
#     name: collabora-CODE
#     description: collabora CODE repo
#     # baseurl: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7
#     # gpgkey: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7/repodata/repomd.xml.key
#     baseurl: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004
#     gpgkey: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004/repodata/repomd.xml.key
#     gpgcheck: "{{ collabora_yum_gpgcheck }}"
#     gpgcheck: no




- name: add collabora apt-key
  ansible.builtin.apt_key:
    url: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7/repodata/repomd.xml.key
    state: present

- name: add collabora apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004 ./'
    # repo: 'deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004'
    state: present
    filename: collabora
    update_cache: yes

- name: install collabora
  ansible.builtin.apt:
    name: [loolwsd, code-brand]
    state: present
    update_cache: yes

# - name: Add APT repo for collabora CODE
#   ansible.builtin.apt_repository:
#     repo: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004
#     state: present




# - name: Install nginx packages
#   yum:
#     name: "{{ vars['nginx_packages_' + ( ansible_distribution | lower ) + ( ansible_distribution_major_version | lower ) ] }}" 
#     state: present
#   when: collabora_nginx_setup

# - name: Install collabora CODE packages
#   yum:
#     name: "{{ vars['collabora_packages_' + ( ansible_distribution | lower ) + ( ansible_distribution_major_version | lower ) ] }}"
#     state: present

# - name: setup new certs if ssl is enabled
#   block:
#     - name: copy internal selfsigned ssl cert creator script
#       template:
#         src: create-collabora-internal-cert.sh.j2
#         dest: /usr/local/sbin/create-collabora-internal-cert.sh
#         owner: root
#         group: root
#         mode: 0700

#     - name: create/update internal self signed cert
#       shell: /usr/local/sbin/create-collabora-internal-cert.sh
#       changed_when: False
#   when: collabora_terminate_ssl

# - name: enable loolwsd service
#   service:
#     name: loolwsd
#     state: started
#     enabled: yes
...
