# joe_speedboat.ansible_collabora/tasks/main.yml
---
- include_tasks: install.yml
  tags: [install]

- include_tasks: configure.yml
  tags: [configure]

- include_tasks: nginx.yml
  tags: [configure]
...
