---
# handlers file for joe_speedboat.ansible_collabora

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart loolwsd
  systemd:
    name: loolwsd
    state: restarted
